version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-docker
  client:
    image: alexey195/accountingclient:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl:ro   # монтируем локальные сертификаты
    restart: unless-stopped
    depends_on:
      - api
  api:
    image: alexey195/accountingapi:latest
    ports:
      - "8888:8888"
    env_file:
      - .env-docker
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting_db
    volumes:
      - accounting_postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    restart: unless-stopped

volumes:
  accounting_postgres_data: